### ISSUE TITLE
Reference !register somewhere [moved]

### ISSUE THREAD

**Issue by its-suun** [brakerb/angoz-addon#10]

**Comment by brakerb** [comment]
It shouldn't be too easy for minges. imo.

**Comment by its-suun** [comment]
1. It doesn't anywhere on the spawn screen mention how to register
2. `!register` automatically registers you without typing anything, easy enough for minges anyways

**Comment by adosikas** [comment]
It should be noted somewhere on the website as it used to be, so im adding this to website issues.

**Comment by its-suun** [comment]
Typing `!register` is as difficult as typing `!acceptrules`. I don't see any way how this could keep minges out

**Comment by adosikas** [comment]
Ideally the reference to !register should be somewhere on the website, and minges would have to find it first, while !acceptrules should be accessible instantly for someone just wanting to play without commiting to registering.
