### ISSUE TITLE
Where is "__PLAYER_NICK" function coming from?

### ISSUE THREAD

**Issue by CaptainPRICE** [brakerb/angoz-addon#17]
`__PLAYER_NICK` function certainly isn't builtin, debugger says it is from C. Why isn't it public?

**Comment by brakerb** [comment]
ProTipp: Stop using Visual Studio to code LUA.

Sorry but no spoort for this addon.

**Comment by CaptainPRICE** [comment]
> Sorry but no spoort for this addon.

... anyway, there is no binary module, it is [fakename addon](https://steamcommunity.com/sharedfiles/filedetails/?id=659490574) which swaps the functions ...
